### ISSUE TITLE
suggestion:

### ISSUE THREAD

**Issue by JosiahParry** [drew-walkerr/PICUDeliriumAndMusicAnalysis#1]
Hey, 

so it looks like you have a data frame with columns that have artist and song - titles.

To iterate over these, individually use code like:

```
df %>%
  mutate(audio_features = map2(artist_column , song_title_column, possible_feats)) %>%
  unnest() %>% 
  as_tibble()
```

`mutate()` lets you create new columns in a data frame. the out put of `possible_feats()` is a tibble. This means you will have a list column. Unnesting expands them. 

`map2()` iterates over two objects. In this case we are passing the columns. It is passing the first argument (`artist_column`) as the first argument to `possible_feats()` and the second argument `song_title_column` as the second argument.

https://github.com/drew-walkerr/HermioneSpotifyDelirium/blob/56a31ec179945bcc7c59fbf5bf6af913b02d1f35/TrackIDfromSongTitleandArtist.R#L45

**Comment by drew-walkerr** [comment]
Thank you so much. Updated.
